branches:
  main:
    regex: ^main$
    increment: Major
    label: ''
    is-main-branch: true
    source-branches: ['release', 'hotfix']

  develop:
    regex: ^dev(elop)?(ment)?$
    increment: Minor
    label: ''
    tracks-release-branches: true
    source-branches: ['main', 'release', 'feature', 'hotfix']

  release:
    regex: ^release[/-]
    increment: Major
    label: beta
    is-release-branch: true
    source-branches: ['develop', 'release']

  hotfix:
    regex: ^hotfix[/-]
    increment: Patch
    label: beta
    source-branches: ['main']

  feature:
    regex: "^features?[\\/-](?<BranchName>.+)"
    increment: Inherit
    label: "feature-{BranchName}"
    source-branches: ['develop', 'feature']

  pull-request:
    regex: "^(pull-requests|pull|pr)[\\/-](?<Number>\\d*)"
    increment: Inherit
    label: 'PullRequest{number}'
    source-branches: ['develop', 'main', 'release', 'feature', 'hotfix']

ignore:
  sha: []
merge-message-formats: {}
