branches:
  main:
    regex: ^main$
    increment: Major
    tag: ''
    is-main-branch: true
    source-branches: ['release', 'hotfix']

  develop:
    regex: ^dev(elop)?(ment)?$
    increment: Minor
    tag: ''
    tracks-release-branches: true
    source-branches: ['main', 'release', 'feature', 'hotfix']

  release:
    regex: ^release[/-]
    increment: Major
    tag: beta
    is-release-branch: true
    source-branches: ['develop', 'release']

  hotfix:
    regex: ^hotfix[/-]
    increment: Patch
    tag: beta
    source-branches: ['main']

  feature:
    regex: ^feature[/-]
    increment: Inherit
    tag: 'feature-{BranchName}'
    source-branches: ['develop', 'feature']

  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    increment: Inherit
    tag: 'PullRequest{number}'
    source-branches: ['develop', 'main', 'release', 'feature', 'hotfix']

ignore:
  sha: []
merge-message-formats: {}
