on:
  workflow_call:
  
  ##############
  # Set the job
  ##############

jobs:
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Note that VALIDATE_PYTHON_FLAKE, VALIDATE_PYTHON_BLACK, VALIDATE_PYTHON_MYPY default values are already true: https://github.com/super-linter/super-linter
      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODE_BASE: false
          ACTIONS_RUNNER_DEBUG: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: false
          SUPPRESS_POSSUM: true
          FILTER_REGEX_INCLUDE: ./agi_valuation_factory
          VALIDATE_PYTHON_BLACK: true
          DEFAULT_BRANCH: main
          LOG_LEVEL: ERROR
         
  
  
